server:
  port: 8085
spring:
  application:
    name: inspire-admin
  profiles:
    active: dev
  sql:
    init:
      mode: never
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
inspire:
  jwt:
    secret: ${INSPIRE_ADMIN_JWT_SECRET}
    expiration: ${INSPIRE_ADMIN_JWT_EXPIRATION:315360000000}
logging:
  level:
    com.inspire: debug
