spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inspire_ai_preview?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&connectionTimeZone=%2B08:00&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: ${INSPIRE_ADMIN_DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
rocketmq:
  name-server: localhost:9876
logging:
  level:
    com.inspire: debug
