server:
  port: 8085
spring:
  application:
    name: inspire-admin
  profiles:
    active: dev
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
inspire:
  jwt:
    secret: dGhpc0lzQURlZmF1bHRTZWNyZXRLZXlGb3JMb2NhbERldk9ubHlQbGVhc2VSZXBsYWNlSW5Qcm9k
    expiration: 604800000
logging:
  level:
    com.inspire: debug
