server:
  port: 8081

spring:
  application:
    name: inspire-auth
  profiles:
    active: dev

  # SQL 初始化
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true

  # 邮件配置（找回密码用）
  mail:
    host: smtp.qq.com
    port: 587
    username: 45257209@qq.com
    password: csqrlhvdxuewbghe
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

mybatis-plus:
  global-config:
    db-config:
      id-type: none
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

inspire:
  jwt:
    secret: dGhpc0lzQURlZmF1bHRTZWNyZXRLZXlGb3JMb2NhbERldk9ubHlQbGVhc2VSZXBsYWNlSW5Qcm9k
    expiration: 604800000
  app:
    frontend-url: http://localhost:5173

logging:
  level:
    com.inspire: debug
    com.baomidou.mybatisplus: info
